# Usa una imagen base de Python
FROM python:3.12-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos del microservicio al contenedor
COPY . .

# Instala las dependencias desde requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Expone el puerto (cambia según el microservicio)
EXPOSE 5000

# Comando para iniciar la app Flask
CMD ["python", "app.py"]
